import importlib
from typing import Any

from tanka.abort import Abort, Status
from tanka.application import (
    Aborted,
    ErrorPage,
    Failsafe,
    Log,
    Logging,
    Silence,
    Tanka,
)
from tanka.asgi import Asgi, AsgiBody
from tanka.auth import (
    AllOf,
    AnyOf,
    Authenticated,
    Authorized,
    IdentitySource,
    Requirement,
    Role,
    Roles,
)
from tanka.body import (
    Body,
    Empty,
    File,
    Gzipped,
    Html,
    Json,
    Raw,
    Stream,
    Text,
)
from tanka.catch import (
    Catch,
    Code,
    Codes,
    Every,
    Fallback,
    Indifferent,
    Listed,
    On,
    Range,
)
from tanka.compression import Compressed
from tanka.cookies import (
    Attribute,
    Cookie,
    CookiePath,
    Cookies,
    Domain,
    ForgetCookie,
    HttpOnly,
    Lifetime,
    SameSite,
    Secure,
    SetCookie,
)
from tanka.cors import (
    AllowCredentials,
    AllowHeaders,
    AllowMethods,
    AllowOrigins,
    Cors,
    ExposeHeaders,
    MaxAge,
    Policy,
    Preflight,
)
from tanka.endpoint import Endpoint
from tanka.flash import (
    Alert,
    Failure,
    Flash,
    Flashes,
    Kind,
    Named,
    Notice,
    Success,
    WithFlash,
)
from tanka.headers import Headers
from tanka.identity import Anonymous, Identity, Principal
from tanka.method import (
    Delete,
    Get,
    Head,
    Method,
    Methods,
    Options,
    Patch,
    Post,
    Put,
    Verb,
)
from tanka.request import Request
from tanka.response import (
    Redirect,
    Reply,
    Response,
    WithCookie,
    WithHeaders,
)
from tanka.routes import Mount, Route, Routes, Rule
from tanka.server import Hypercorn, Once, Reload, Server, Uvicorn, Watch
from tanka.static import Directory, Files, Static
from tanka.target import Path, Query, Target
from tanka.templates import Context, JsonReadable, Pair, Template, Templates

__all__ = [
    "Abort",
    "Aborted",
    "Alert",
    "AllOf",
    "AllowCredentials",
    "AllowHeaders",
    "AllowMethods",
    "AllowOrigins",
    "Anonymous",
    "AnyOf",
    "Asgi",
    "AsgiBody",
    "Attribute",
    "Authenticated",
    "Authorized",
    "Body",
    "Catch",
    "Code",
    "Codes",
    "Compressed",
    "Context",
    "Cookie",
    "CookiePath",
    "Cookies",
    "Cors",
    "Delete",
    "Directory",
    "Domain",
    "Empty",
    "Endpoint",
    "ErrorPage",
    "Every",
    "ExposeHeaders",
    "Failsafe",
    "Failure",
    "Fallback",
    "File",
    "Files",
    "Flash",
    "Flashes",
    "ForgetCookie",
    "Get",
    "Gzipped",
    "Head",
    "Headers",
    "Html",
    "HttpOnly",
    "Hypercorn",
    "Identity",
    "IdentitySource",
    "Indifferent",
    "Jinja",
    "Json",
    "JsonReadable",
    "Kind",
    "Lifetime",
    "Listed",
    "Log",
    "Logging",
    "MaxAge",
    "Method",
    "Methods",
    "Mount",
    "Named",
    "Notice",
    "On",
    "Once",
    "OpenApi",
    "Options",
    "Pair",
    "Patch",
    "Path",
    "Policy",
    "Post",
    "Preflight",
    "Principal",
    "Put",
    "Query",
    "Range",
    "Raw",
    "Redirect",
    "Reload",
    "Reply",
    "Request",
    "Requirement",
    "Response",
    "Role",
    "Roles",
    "Route",
    "Routes",
    "Rule",
    "SameSite",
    "Secure",
    "Server",
    "SetCookie",
    "Silence",
    "Static",
    "Status",
    "Stream",
    "Success",
    "Tanka",
    "Target",
    "Template",
    "Templates",
    "Text",
    "Uvicorn",
    "Verb",
    "Watch",
    "WithCookie",
    "WithFlash",
    "WithHeaders",
]


def __getattr__(name: str) -> Any:
    modules = {"OpenApi": "tanka.openapi", "Jinja": "tanka.jinja"}
    if name not in modules:
        raise AttributeError(f"module 'tanka' has no attribute '{name}'")
    return getattr(importlib.import_module(modules[name]), name)
