from typing import Any

from tanka.abort import Abort, Status
from tanka.application import (
    Aborted,
    ErrorPage,
    Failsafe,
    Log,
    Logging,
    Silence,
    Tanka,
)
from tanka.asgi import Asgi, AsgiBody
from tanka.auth import (
    AllOf,
    AnyOf,
    Authenticated,
    Authorized,
    IdentitySource,
    Requirement,
    Role,
    Roles,
)
from tanka.body import Body, Empty, File, Html, Json, Raw, Stream, Text
from tanka.catch import (
    Catch,
    Code,
    Codes,
    Every,
    Fallback,
    Indifferent,
    Listed,
    On,
    Range,
)
from tanka.cookies import (
    Attribute,
    Cookie,
    CookiePath,
    Cookies,
    Domain,
    ForgetCookie,
    HttpOnly,
    Lifetime,
    SameSite,
    Secure,
    SetCookie,
)
from tanka.cors import (
    AllowCredentials,
    AllowHeaders,
    AllowMethods,
    AllowOrigins,
    Cors,
    ExposeHeaders,
    MaxAge,
    Policy,
    Preflight,
)
from tanka.endpoint import Endpoint
from tanka.flash import (
    Alert,
    Failure,
    Flash,
    Flashes,
    Kind,
    Named,
    Notice,
    Success,
    WithFlash,
)
from tanka.headers import Headers
from tanka.identity import Anonymous, Identity, Principal
from tanka.method import (
    Delete,
    Get,
    Head,
    Method,
    Methods,
    Options,
    Patch,
    Post,
    Put,
    Verb,
)
from tanka.request import Request
from tanka.response import Redirect, Reply, Response, WithCookie, WithHeaders
from tanka.routes import Mount, Route, Routes, Rule
from tanka.server import Hypercorn, Once, Reload, Server, Uvicorn, Watch
from tanka.static import Directory, Files, Static
from tanka.target import Path, Query, Target

__all__ = [
    "Abort",
    "Aborted",
    "Alert",
    "AllOf",
    "AllowCredentials",
    "AllowHeaders",
    "AllowMethods",
    "AllowOrigins",
    "Anonymous",
    "AnyOf",
    "Asgi",
    "AsgiBody",
    "Attribute",
    "Authenticated",
    "Authorized",
    "Body",
    "Catch",
    "Code",
    "Codes",
    "Cookie",
    "CookiePath",
    "Cookies",
    "Cors",
    "Delete",
    "Directory",
    "Domain",
    "Empty",
    "Endpoint",
    "ErrorPage",
    "Every",
    "ExposeHeaders",
    "Failsafe",
    "Failure",
    "Fallback",
    "File",
    "Files",
    "Flash",
    "Flashes",
    "ForgetCookie",
    "Get",
    "Head",
    "Headers",
    "Html",
    "HttpOnly",
    "Hypercorn",
    "Identity",
    "IdentitySource",
    "Indifferent",
    "Json",
    "Kind",
    "Lifetime",
    "Listed",
    "Log",
    "Logging",
    "MaxAge",
    "Method",
    "Methods",
    "Mount",
    "Named",
    "Notice",
    "On",
    "Once",
    "OpenApi",
    "Options",
    "Patch",
    "Path",
    "Policy",
    "Post",
    "Preflight",
    "Principal",
    "Put",
    "Query",
    "Range",
    "Raw",
    "Redirect",
    "Reload",
    "Reply",
    "Request",
    "Requirement",
    "Response",
    "Role",
    "Roles",
    "Route",
    "Routes",
    "Rule",
    "SameSite",
    "Secure",
    "Server",
    "SetCookie",
    "Silence",
    "Static",
    "Status",
    "Stream",
    "Success",
    "Tanka",
    "Target",
    "Text",
    "Uvicorn",
    "Verb",
    "Watch",
    "WithCookie",
    "WithFlash",
    "WithHeaders",
]


def __getattr__(name: str) -> Any:
    if name != "OpenApi":
        raise AttributeError(f"module 'tanka' has no attribute '{name}'")
    from tanka.openapi import OpenApi

    return OpenApi
